### ISSUE TITLE
CSS validator issues

### ISSUE THREAD

**Issue by LordZUL** [imd1005-web-development-winter-2023/assignment-03-LordZUL#3]
**Describe the bug**
Hello Mr. Neil, @neilmispelaar 
This is not really a bug, but just a quick question.

On the validator that Chrisitan and I did, the CSS seems to have a lot of issues, but the highlighted codes are not in my actual CSS file based on his screenshots? and on mine it says there is no issue but then proceeds to list 49 issues? 

Thanks, 
Alanna

**To Reproduce**
1. Go to '[https://jigsaw.w3.org/css-validator/]'
2. insert live repos website link

**Expected behavior**
There shouldn't be so much issues ;-;

**Screenshots**
(![Screenshot 2023-03-19 133822](https://user-images.githubusercontent.com/122396273/226197722-230d2291-8f52-469a-8903-d75abc715482.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Smartphone**
please complete the following information):**

**Additional context**

**Comment by neilmispelaar** [comment]
I just checked as well and you don't have any issues:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-03-LordZUL%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en 

It's possible the wrong URL was pasted into the input field or something else wonky happened. 

No worries though - your code passes both HTML and CSS validation so nothing to worry about.
